#!/usr/bin/env python3
"""Download a video via yt-dlp, or resolve a local file path.

Also fetches subtitles (manual first, then auto-generated) in VTT format so
transcribe.py can parse them without needing Whisper.
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from urllib.parse import urlparse


VIDEO_EXTS = {".mp4", ".mkv", ".webm", ".mov", ".m4v", ".avi", ".flv", ".wmv"}


def _cookie_string_to_file(cookie_string: str, url: str) -> str:
    """Convert a raw Cookie header string (e.g. from F12 → Network) to a
    Netscape-format cookies.txt file that yt-dlp can consume via ``--cookies``.

    Returns the path to a temporary file. The caller is responsible for cleanup.
    """
    parsed = urlparse(url)
    domain = parsed.hostname or ""
    # Leading dot makes the cookie match all subdomains (Netscape spec).
    if domain and not domain.startswith("."):
        domain = "." + domain

    expiry = int(time.time()) + 7 * 86400  # 7 days from now
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by watch skill (cookie-string mode)",
        f"# Source domain: {domain}",
    ]
    for pair in cookie_string.split(";"):
        pair = pair.strip()
        if not pair or "=" not in pair:
            continue
        name, _, value = pair.partition("=")
        name = name.strip()
        value = value.strip()
        if not name:
            continue
        # domain  include_subdomain  path  secure  expiration  name  value
        lines.append(f"{domain}\tTRUE\t/\tTRUE\t{expiry}\t{name}\t{value}")

    fd, tmp_path = tempfile.mkstemp(suffix=".txt", prefix="watch_cookies_")
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return tmp_path


def _resolve_cookies(
    cookies_file: str | None,
    cookie_string: str | None,
    url: str,
) -> tuple[list[str], str | None]:
    """Return ``(yt_dlp_args, temp_path_to_clean)`` for cookie injection.

    - ``cookies_file`` (path to a Netscape cookies.txt) takes precedence.
    - ``cookie_string`` (raw Cookie header) is converted to a temp Netscape file.
    - If neither is set, returns ``([], None)``.
    """
    if cookies_file:
        p = Path(cookies_file).expanduser()
        if not p.exists():
            raise SystemExit(f"Cookie file not found: {p}")
        return (["--cookies", str(p)], None)

    if cookie_string:
        tmp = _cookie_string_to_file(cookie_string, url)
        return (["--cookies", tmp], tmp)

    return ([], None)


def is_url(source: str) -> bool:
    if source.startswith("-"):
        return False
    parsed = urlparse(source)
    return parsed.scheme in ("http", "https") and bool(parsed.netloc)


def resolve_local(path: str) -> dict:
    p = Path(path).expanduser().resolve()
    if not p.exists():
        raise SystemExit(f"File not found: {p}")
    if p.suffix.lower() not in VIDEO_EXTS:
        print(
            f"[watch] warning: {p.suffix} is not a known video extension, proceeding anyway",
            file=sys.stderr,
        )
    return {
        "video_path": str(p),
        "subtitle_path": None,
        "info": {"title": p.name, "url": str(p)},
        "downloaded": False,
    }


def _pick_subtitle(out_dir: Path) -> Path | None:
    candidates = sorted(out_dir.glob("video*.vtt"))
    if not candidates:
        return None
    preferred = [
        c for c in candidates
        if any(marker in c.name for marker in (".en.", ".en-US.", ".en-GB.", ".en-orig."))
    ]
    return preferred[0] if preferred else candidates[0]


def _pick_video(out_dir: Path) -> Path | None:
    for ext in (".mp4", ".mkv", ".webm", ".mov", ".m4a", ".mp3", ".opus"):
        for candidate in out_dir.glob(f"video*{ext}"):
            return candidate
    for candidate in out_dir.glob("video.*"):
        if candidate.suffix.lower() in VIDEO_EXTS:
            return candidate
    return None


def fetch_captions(
    url: str,
    out_dir: Path,
    cookies_file: str | None = None,
    cookie_string: str | None = None,
) -> dict:
    """Fetch metadata and best available VTT captions without downloading video."""
    if shutil.which("yt-dlp") is None:
        raise SystemExit("yt-dlp is not installed. Install with: brew install yt-dlp")

    out_dir.mkdir(parents=True, exist_ok=True)
    output_template = str(out_dir / "video.%(ext)s")
    cookie_args, cookie_tmp = _resolve_cookies(cookies_file, cookie_string, url)
    cmd = [
        "yt-dlp",
        "--skip-download",
        "--write-info-json",
        "--write-subs",
        "--write-auto-subs",
        "--sub-langs", "en.*",
        "--sub-format", "vtt",
        "--convert-subs", "vtt",
        "--no-playlist",
        "--ignore-errors",
        *cookie_args,
        "-o", output_template,
        "--",
        url,
    ]
    try:
        subprocess.run(cmd, stdout=sys.stderr, stderr=sys.stderr)
    finally:
        if cookie_tmp:
            os.unlink(cookie_tmp)
    subtitle = _pick_subtitle(out_dir)
    info = _read_info(out_dir / "video.info.json", url)
    return {
        "video_path": None,
        "subtitle_path": str(subtitle) if subtitle else None,
        "info": info or {"url": url},
        "downloaded": False,
    }


def _read_info(info_path: Path, url: str) -> dict:
    info: dict = {}
    if info_path.exists():
        try:
            raw = json.loads(info_path.read_text(encoding="utf-8"))
            info = {
                "title": raw.get("title"),
                "uploader": raw.get("uploader") or raw.get("channel"),
                "duration": raw.get("duration"),
                "url": raw.get("webpage_url") or url,
            }
        except Exception as exc:
            print(f"[watch] info.json parse failed: {exc}", file=sys.stderr)
            info = {"url": url}
    return info


def download_url(
    url: str,
    out_dir: Path,
    audio_only: bool = False,
    cookies_file: str | None = None,
    cookie_string: str | None = None,
) -> dict:
    if shutil.which("yt-dlp") is None:
        raise SystemExit("yt-dlp is not installed. Install with: brew install yt-dlp")

    out_dir.mkdir(parents=True, exist_ok=True)
    output_template = str(out_dir / "video.%(ext)s")

    fmt = "ba/bestaudio" if audio_only else "bv*[height<=720]+ba/b[height<=720]/bv+ba/b"
    cookie_args, cookie_tmp = _resolve_cookies(cookies_file, cookie_string, url)
    cmd = [
        "yt-dlp",
        "-N", "8",
        "-f", fmt,
        "--merge-output-format", "mp4",
        "--write-info-json",
        "--write-subs",
        "--write-auto-subs",
        "--sub-langs", "en.*",
        "--sub-format", "vtt",
        "--convert-subs", "vtt",
        "--no-playlist",
        "--ignore-errors",
        *cookie_args,
        "-o", output_template,
        "--",
        url,
    ]

    # yt-dlp may exit non-zero if a subtitle variant fails (e.g. 429) even when
    # the video itself downloaded fine. Treat "video file present" as success.
    try:
        result = subprocess.run(cmd, stdout=sys.stderr, stderr=sys.stderr)
    finally:
        if cookie_tmp:
            os.unlink(cookie_tmp)
    video = _pick_video(out_dir)
    if video is None:
        raise SystemExit(
            f"yt-dlp did not produce a video file in {out_dir} (exit {result.returncode})"
        )

    subtitle = _pick_subtitle(out_dir)
    info = _read_info(out_dir / "video.info.json", url)

    return {
        "video_path": str(video),
        "subtitle_path": str(subtitle) if subtitle else None,
        "info": info or {"url": url},
        "downloaded": True,
    }


def download(
    source: str,
    out_dir: Path,
    audio_only: bool = False,
    cookies_file: str | None = None,
    cookie_string: str | None = None,
) -> dict:
    if is_url(source):
        return download_url(
            source,
            out_dir,
            audio_only=audio_only,
            cookies_file=cookies_file,
            cookie_string=cookie_string,
        )
    return resolve_local(source)


if __name__ == "__main__":
    import argparse

    ap = argparse.ArgumentParser(
        prog="download.py",
        description="Download a video or fetch captions via yt-dlp.",
    )
    ap.add_argument("source", help="Video URL or local file path")
    ap.add_argument("out_dir", help="Output directory")
    ap.add_argument("--audio-only", action="store_true", help="Download audio only")
    ap.add_argument(
        "--cookies",
        type=str,
        default=None,
        help="Path to a Netscape-format cookies.txt file for login-walled sites.",
    )
    ap.add_argument(
        "--cookie-string",
        type=str,
        default=None,
        help='Raw Cookie header string (e.g. from F12 Network tab). '
        'Automatically converted to a temp cookies.txt for yt-dlp.',
    )
    args = ap.parse_args()

    result = download(
        args.source,
        Path(args.out_dir),
        audio_only=args.audio_only,
        cookies_file=args.cookies,
        cookie_string=args.cookie_string,
    )
    print(json.dumps(result, indent=2))
